pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               
                dir('DemoQAAutomation') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('DemoQAAutomation') {
                    bat 'mvn test'
                }
            }
        }

        stage('Report') {
            steps {
                dir('DemoQAAutomation') {
                    // This publishes the HTML report generated by Maven/TestNG
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target',
                        reportFiles: 'index.html',
                        reportName: 'Extent Report'
                    ])
                }
            }
        }
    }
}
